### ISSUE TITLE
NameError: global name 'm' is not defined

### ISSUE THREAD

**Issue by alihalabyah** [vesche/scanless#2]
Hi,

I'm getting the below error, Any ideas?

```
Running scanless...
Traceback (most recent call last):
  File "scanless.py", line 80, in <module>
    main()
  File "scanless.py", line 76, in main
    scanless(target, scanner)
  File "scanless.py", line 40, in scanless
    print(run(scanner))
  File "scanless.py", line 32, in run
    return 'Error, {} was unable to run.'.format(m)
NameError: global name 'm' is not defined
```

**Comment by ubalot** [comment]
try this: substitute 'm' with 's'.
you should get in output the name of the scanner that get the error.

**Comment by vesche** [comment]
Whoops, thanks for pointing this out. Fixed with the latest commit.
